### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by mkosunen**
@chiplet @Roenski  FYI, Started the refactoring. I have tested the changes so far with inverter and inverter_tests, and the operation is as it is with current v1.9_RC branch, commit  30941e9e8c75b5ecb2.

Idea behind:
All simulator specific stuff goes to simulator specific classes.
All language specific goes to language specific classes.

Simulators may or may not support several languages.  E.g. questasim support both vhdl and verilog, but Icarus does not.

Later on the 'model' parameter will be split to two parameters 'simulator' and 'lang' with checks for valid combinations, and hopefully with some banckwards compatibility.

If you have time, please run your current simulations with this branch to see if something broke and let me know.

### CODE REVIEW

**Comment by mkosunen** [comment]
@Roenski @chiplet , First pass of refactoring done. This should still be fully backwards compatible. Could you test that I did not break anything. I have tested the changes with inverter using all rtl simulators. (Icarus of the lab still too old to work)

Once I get OK from you' I'll merge.

**Comment by mkosunen** [comment]
See also if you wish: https://github.com/TheSystemDevelopmentKit/thesdk_template/pull/23

**Comment by Roenski** [comment]
I tested it with A-Core using icarus backend that works with latest v1.9_RC and something doesn't work. The rtl command throws the following error
```
ELABORATING DESIGN
repodir/a-core_thesydekick/Entities/ACoreChip/simulations/sv/20221122095042_tmp5vne2to9/rtl/ACoreChip.v:9770: error: Unknown module type: AsyncResetSyncBB
2 error(s) during elaboration.
*** These modules were missing:
        AsyncResetSyncBB referenced 1 times.
***
```

Simulation command looks like this:
```
iverilog -Wall -v -g2012 -o /u/52/korsmaa1/data/Documents/a-core_thesydekick/Entities/ACoreChip/simulations/sv/20221122095042_tmp5vne2to9/work/ACoreChip/u/52/korsmaa1/data/Documents/a-core_thesydekick/Entities/ACoreChip/simulations/sv/20221122095042_tmp5vne2to9/rtl/AsyncResetSyncBB.v /u/52/korsmaa1/data/Documents/a-core_thesydekick/Entities/ACoreChip/simulations/sv/20221122095042_tmp5vne2to9/rtl/ACoreChip.v /u/52/korsmaa1/data/Documents/a-core_thesydekick/Entities/ACoreChip/simulations/sv/20221122095042_tmp5vne2to9/rtl/tb_ACoreChip.v && sync /u/52/korsmaa1/data/Documents/a-core_thesydekick/Entities/ACoreChip/simulations/sv/20221122095042_tmp5vne2to9/work && vvp -v /u/52/korsmaa1/data/Documents/a-core_thesydekick/Entities/ACoreChip/simulations/sv/20221122095042_tmp5vne2to9/work/ACoreChip && gtkwave -S/u/52/korsmaa1/data/Documents/a-core_thesydekick/Entities/ACoreChip/interactive_control_files/gtkwave/general.tcl ACoreChip_dump.vcd
```
The path for `AsyncResetSyncBB` looks weird, and is something that was fixed in https://github.com/TheSystemDevelopmentKit/rtl/commit/0fb615bc67593961d9a39756442ebe704eaee344. So I'm assuming you have not yet merged this change to this branch?

**Comment by mkosunen** [comment]
@Roenski did not merge https://github.com/TheSystemDevelopmentKit/rtl/commit/0fb615bc67593961d9a39756442ebe704eaee344 as merging to refactoerc code might be tedious. Anyway. I'll try to adopt the changes without breaking anything.
